[build]
# target = "xtensa-esp32-espidf"
# target = "xtensa-esp32s2-espidf"
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"]

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
ESP_IDF_VERSION = "v5.1.2"
